iso639_3_to_bert_language = {
    'ara': 'ar_AR',
    'ces': 'cs_CZ',
    'deu': 'de_DE',
    'eng': 'en_XX',
    'spa': 'es_XX',
    'est': 'et_EE',
    'fin': 'fi_FI',
    'fra': 'fr_XX',
    'guj': 'gu_IN',
    'hin': 'hi_IN',
    'ita': 'it_IT',
    'jpn': 'ja_XX',
    'kaz': 'kk_KZ',
    'kor': 'ko_KR',
    'lit': 'lt_LT',
    'lav': 'lv_LV',
    'mya': 'my_MM',
    'nep': 'ne_NP',
    'nld': 'nl_XX',
    'ron': 'ro_RO',
    'rus': 'ru_RU',
    'sin': 'si_LK',
    'tur': 'tr_TR',
    'vie': 'vi_VN',
    'zho': 'zh_CN',
    'afr': 'af_ZA',
    'aze': 'az_AZ',
    'ben': 'bn_IN',
    'fas': 'fa_IR',
    'heb': 'he_IL',
    'hrv': 'hr_HR',
    'ind': 'id_ID',
    'kat': 'ka_GE',
    'khm': 'km_KH',
    'mkd': 'mk_MK',
    'mal': 'ml_IN',
    'mon': 'mn_MN',
    'mar': 'mr_IN',
    'pol': 'pl_PL',
    'pus': 'ps_AF',
    'por': 'pt_XX',
    'swe': 'sv_SE',
    'swa': 'sw_KE',
    'tam': 'ta_IN',
    'tel': 'te_IN',
    'tha': 'th_TH',
    'tgl': 'tl_XX',
    'ukr': 'uk_UA',
    'urd': 'ur_PK',
    'xho': 'xh_ZA',
    'glg': 'gl_ES',
    'slv': 'sl_SI',
}


languages_available_in_bert_iso639_3_set = {
    'ara', 'ces', 'deu', 'eng', 'spa', 'est', 'fin', 'fra', 'guj', 'hin',
    'ita', 'jpn', 'kaz', 'kor', 'lit', 'lav', 'mya', 'nep', 'nld', 'ron',
    'rus', 'sin', 'tur', 'vie', 'zho', 'afr', 'aze', 'ben', 'fas', 'heb',
    'hrv', 'ind', 'kat', 'khm', 'mkd', 'mal', 'mon', 'mar', 'pol', 'pus',
    'por', 'swe', 'swa', 'tam', 'tel', 'tha', 'tgl', 'ukr', 'urd', 'xho',
    'glg', 'slv'
}